### ISSUE TITLE
Config server does not reload configuration

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud-samples/configserver#10]
Hi there,

I tried configuring the server without Redis and Monitoring...

```xml
                <dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-config-server</artifactId>
                </dependency>
                <!--dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-config-monitor</artifactId>
                </dependency>
                <dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-starter-stream-redis</artifactId>
                </dependency-->
                <dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-starter-eureka</artifactId>
                </dependency>
```

However, any changes to the GitHub configuration repository was not picked up by the server... 

Questions
-----

* Is it possible to run the server without Redis?
* Leaving the monitor settings uncommented, the server cannot start. Is this only used by Redis?
* How to configure a webhook in GitHub? Is this http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus automatically done by the config server?

**Comment by spencergibb** [comment]
You need to setup a webhook with github manually. It is not done automatically. https://developer.github.com/webhooks/creating/

**Comment by marcellodesales** [comment]
@spencergibb Thank you, but what's the endpoint that GitHub needs to call on the config server??? I haven't found in the documentation...

**Comment by spencergibb** [comment]
According to [the docs](https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#push-notifications-and-spring-cloud-bus) it's `/monitor`.

**Comment by marcellodesales** [comment]
@spencergibb Perfect... Thanks a lot for the info!
