### ISSUE TITLE
there is some thing wrong when i try to execut this command ./mvnw spring-boot:run

### ISSUE THREAD

**Issue by learonlizheng** [spring-cloud-samples/configserver#16]
No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories

**Comment by spencergibb** [comment]
I'm unable to recreate. Maybe use `./mvn -U` to update your dependencies? Maybe you're behind a proxy?

**Comment by 625096233** [comment]
Project build error: 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-stream-redis:jar is missing.

**Comment by spencergibb** [comment]
@sukyology we had some issues with artifactory recently. spring-cloud-commons 1.1.8.BUILD-SNAPSHOT is there again.
