### ISSUE TITLE
POM file has a potentially outdated spring cloud dependency

### ISSUE THREAD

**Issue by ddubson** [spring-cloud-samples/configserver#17]
Running `./mvnw spring-boot:run` for the first time does not find appropriate dependencies for version `Brixton.BUILD-SNAPSHOT` of spring cloud starter and fails to run the Spring Boot app. Changing the dependency version to `Brixton.SR1` (labeled current on http://projects.spring.io/spring-cloud/) resolves the issue. I'd be happy to create a PR for this issue if my findings are valid.

**Comment by spencergibb** [comment]
No, there some other problem with our snapshots.

**Comment by spencergibb** [comment]
Check now, we've fixed the snapshots of starters.

**Comment by ddubson** [comment]
Works as expected. Great!
