### ISSUE TITLE
Fix the last line of README.md

### ISSUE THREAD

**Issue by maxxyme** [spring-cloud-samples/configserver#20]
Hello, the last line of the readme is a nonsense, it's a password but has a java command in it:
`$ KEYSTORE_PASSWORD=foobar java -jar target/*.jar`

https://github.com/spring-cloud-samples/configserver/blob/master/README.md

Cheers.

**Comment by spencergibb** [comment]
That's standard shell script to set an environment variable before a command

**Comment by maxxyme** [comment]
Not standard under Windows...

**Comment by spencergibb** [comment]
hence the `$`
