### ISSUE TITLE
not secured?

### ISSUE THREAD

**Issue by waffel** [spring-cloud-samples/configserver#8]
Hi,

I have cloned the project and started the service. But it is not secured per default (no http basic auth). But it is described in the README.md that this server is secured per default.

How can I enable the basic authentification (the bset would be only for the /admin mapping)?

Thanks

**Comment by dsyer** [comment]
You can enable basic auth by adding Spring Security to the classpath (per the Spring Boot docs). I'll fix the README, thanks.

**Comment by dsyer** [comment]
Actually it says in the README "The server is not secure by default". I guess it was already fixed.
